pipeline:
  name: Pipeline validation - precommit hooks
  identifier: Pipeline_validation_precommit_hooks
  projectIdentifier: Reference_Architecture
  orgIdentifier: demo
  tags:
    owner: danf
  stages:
    - stage:
        name: ValidYAML
        identifier: Valid
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
